apiVersion: apps/v1
kind: Deployment
metadata:
  name: lp-app-deployment
  labels:
    app: lp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lp-app
  template:
    metadata:
      labels:
        app: lp-app
    spec:
      initContainers:
      - name: wait-for-db
        image: busybox
        command: ['sh', '-c', 'until nc -z postgres 5432; do echo waiting for db; sleep 2; done;']
      - name: wait-for-rabbitmq
        image: busybox
        command: ['sh', '-c', 'until nc -z rabbitmq 5672; do echo waiting for rabbitmq; sleep 2; done;']
      - name: wait-for-redis
        image: busybox
        command: ['sh', '-c', 'until nc -z redis 6379; do echo waiting for redis; sleep 2; done;']
      containers:
      - name: lp-container
        image: lp-app:1.0.0
        ports:
        - containerPort: 8002
        env:
          - name: CONFIG_PATH
            value: "/lp/config.yml"
        volumeMounts:
          - mountPath: /lp/config.yml
            subPath: config.yml
            name: config-volume
      volumes:
      - name: config-volume
        configMap:
          name: lp-config
