apiVersion: v1
kind: ConfigMap
metadata:
  name: lp-config
data:
  config.yml: |
    grpc_server:
      address: ":8002"
      timeout: "2s"
    storage:
      type: postgres
      host: postgres
      port: 5432
      user: postgres
      password: postgres
      dbname: postgres
    rabbit_mq:
      host: rabbitmq
      port: 5672
      username: guest
      password: guest
      share_exchange:
        name: share
        kind: direct
        durable: true
        auto_deleted: false
        internal: false
        no_wait: false
        args:
          alternate_exchange: alternate_exchange_share
      channel:
        channel_queue:
          name: channel
          durable: true
          auto_deleted: false
          exclusive: false
          no_wait: false
        channel_consumer:
          queue: channel
          consumer: ""
          autoAck: false
          exclusive: false
          noLocal: false
          noWait: false
          args:
            x-consumer-timeout: 60000
            x-consumer-prefetch-count: 5
        channel_routing_key: channel
      plan:
        plan_queue:
          name: plan
          durable: true
          auto_deleted: false
          exclusive: false
          no_wait: false
        plan_routing_key: plan
        plan_consumer:
          queue: plan
          consumer: ""
          autoAck: false
          exclusive: false
          noLocal: false
          noWait: false
          args:
            x-consumer-timeout: 60000
            x-consumer-prefetch-count: 5
      notification:
        notification_queue:
          name: notification_to_auth
          durable: true
          auto_deleted: false
          exclusive: false
          no_wait: false
        notification_routing_key: notification_to_auth
      spfu:
        spfu_consumer:
          queue: spfu
          consumer: ""
          autoAck: false
          exclusive: false
          noLocal: false
          noWait: false
          args:
            x-consumer-timeout: 60000
            x-consumer-prefetch-count: 5
    redis:
      host: redis
      port: 6379
      attemts_db: 3
      password: ""
    clients:
      sso:
        address: "sso-app-service:50051"
        timeout: "2s"
        retries_count: 3
        insecure: false