apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
data:
  POSTGRES_USER: "postgres"
  POSTGRES_PASSWORD: "postgres"
  POSTGRES_DB: "postgres"
  DB_HOST: "db"
  DB_PORT: "5432"
  DB_NAME: "postgres"
  DB_USER: "postgres"
  DB_PASS: "postgres"
  MIGRATIONS_PATH: "/migrations"
  MIGRATIONS_TABLE: "schema_migrations"