apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-pvs
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  volumeName: mongo-pv
  storageClassName: standard